[build.environment]
  NODE_VERSION = "18"

[build]
  base = "pagina-de-acesso/front-end"
  command = "npm run build"
  publish = "pagina-de-acesso/front-end/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


