[build.environment]
NODE_VERSION = "18"

[build]
command = "npm run build"
publish = "dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
from = "/api/*"
to = "http://localhost:3000/:splat"
status = 200
force = true